team-yaza/mozi-client

.babelrc
package.json
public/index.html
src/App.tsx
src/index.tsx
tsconfig.json
webpack.config.js
yarn.lock

webpack 기본 설정 후 yarn dev 명령어를 통해 로컬에서 실행하였습니다.
webpack 설정 추후에 공부하면서 더 이쁘게 해봅시다

chore: webpack 설정

---

.prettierrc

chore: prettier 설정 추가

---

jest.config.js
package.json
yarn.lock

- 업무에 대한 설명
- 연관된 이슈
- 코드 리뷰시 중점적으로 봐줬으면 하는 부분

chore: jest

---

package.json
pages/_app.tsx
pages/index.tsx
shared/utils/queryClient.ts
yarn.lock

feat: react-query 적용

---

package.json
pages/_app.tsx
pages/index.test.tsx
pages/index.tsx
shared/api/apiClient.ts
styles/globalStyle.ts
yarn.lock

- 업무에 대한 설명
- 연관된 이슈
- 코드 리뷰시 중점적으로 봐줬으면 하는 부분

feat: main page layout

---

pages/index.tsx

- 업무에 대한 설명
- 연관된 이슈
- 코드 리뷰시 중점적으로 봐줬으면 하는 부분

feat: 할 일 추가 화면 및 요청 보내기

---

cypress/e2e/app.cy.ts
pages/index.tsx
shared/api/apiClient.ts
shared/api/todoAPI.ts
tests/pages/index.test.tsx

- 할일 목록 표시 / 페이지 표현
- API 데이터 받아오기
- 데이터 보여주기
- 페어 프로그래밍으로 진행하였습니다.

feat: todo list

---

pages/index.tsx

- 업무에 대한 설명
- 연관된 이슈
- 코드 리뷰시 중점적으로 봐줬으면 하는 부분

feat: 할일 삭제 버튼 및 삭제 요청

---

pages/index.tsx
shared/api/todoAPI.ts

- 업무에 대한 설명
- 연관된 이슈
- create 로직 개선
- delete 로직 개선
- useCallBack 사용하여 성능 개선
- 페어프로그래밍으로 진행하였습니다.

refactor: main page api logic

---

components/TestComponent.tsx
components/index/TodoList/index.tsx
components/index/TodoSubmitForm/index.tsx
pages/index.tsx
shared/api/todoAPI.ts
shared/types/todo.ts

- 업무에 대한 설명
- 연관된 이슈
- 페어 프로그래밍으로 진행하였습니다.

refactor: Main Page

---

components/sidebar/index.tsx
components/sidebar/menu/index.tsx
components/sidebar/menu/style.tsx
components/sidebar/styled.tsx
pages/index.tsx
shared/types/menu.ts

사이드바 간단하게 구현하였습니다.
- menu 컴포넌트 구현
- side bar 컴포넌트 구현
- 그에 따른 main page 로직 변경
- 사이드 바 메뉴의 아이콘이 아직 안정해져서 그냥 일단은 Url로 해놨습니다.

feature: side bar

---

.eslintrc.js
package.json
yarn.lock

chore: eslint next plugin 추가

---

components/index/TodoListItem/index.tsx
shared/api/todoApi.ts

- react 쿼리 사용해 todo 변경 (#66)
- api 요청 보내는 로직 구현 (#67)
https://user-images.githubusercontent.com/51700274/179992036-19f99110-2f30-4d78-bc61-3bcf5acba31b.mov
리액트 쿼리 처음 써보고,,, 어떻게 쓰는지 몰라서 그냥 위에 적힌대로 보고 썼는데,,, 잘 했는지 이 부분 중점적으로 봐주시고 리액트 쿼리 잘 정리되어있는 레퍼런스 추천 부탁드려용 :)

feat: update todo

---

.eslintrc.js
pages/_app.tsx
public/sw.js

- 서비스 워커 만들기
- 서비스 워커 등록
테스트로 모든 fetch 요청에 대해 console을 찍으라고 했는데 잘 되는 모습입니다.
테스트로는 잘 되지만 캐싱이라던지 백그라운드에서 요청을 보낸다던지 혹은 코르도바와 호환이 잘 될지 걱정이 많습니다..

feat: register service worker

---

.eslintrc.js
.gitignore
components/index/TodoListItem/index.tsx
next.config.js
package.json
pages/_app.tsx
public/sw.js
shared/api/todoApi.ts
shared/types/service-worker.d.ts
worker/index.ts
yarn.lock

next에 적합하도록 service worker를 등록하였습니다.
추가로 typescript로 서비스 워커를 사용할 수 있도록 설정하였습니다.
- next-pwa 적용
- 서비스 워커 타입스크립트 적용
- 서비스 워커 등록
- next-pwa 에서 서비스 워커를 자동으로 추적해서 등록해버린다... 완전 신기하다...
- [참고 레퍼런스](https://github.com/shadowwalker/next-pwa/tree/master/examples/custom-ts-worker)

refactor: service worker 등록

---

components/common/Sidebar/index.tsx
components/map/SearchInput/index.tsx
components/map/SearchInput/styles.tsx
hooks/useMap.ts
next.config.js
pages/map/index.tsx
styles/globalStyle.ts
utils/fetcher.ts

사용자는 지도에서 특정 위치를 검색할 수 있다.
- map 페이지에 인풋 박스 컴포넌트 만듦
- 엔터로 요청을 보내면 그 장소로 지도 이동 및 마커찍기
https://user-images.githubusercontent.com/63354527/180592411-5753e613-8ec9-4123-acd0-1e018c212178.mov
이게 동영상이 10mb 밖에 안되네요 -_-

feat: 지도 검색 기능 및 마커 찍기

---

hooks/useDebounce/index.test.tsx
hooks/useDebounce/index.ts

useDebounce 훅 
```js
import React, { ChangeEvent, useEffect, useState } from 'react'
import { useDebounce } from '.'
export default function Component() {
const [value, setValue] = useState('')
const debouncedValue = useDebounce(value, 500)
const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
setValue(event.target.value)
}
useEffect(() => {
// api fetch (debounceValue가 바뀌면)
}, [debouncedValue])
return (
<div>
<p>Value real-time: {value}</p>
<p>Debounced value: {debouncedValue}</p>
<input type="text" value={value} onChange={handleChange} />
</div>
)
}
```

feat: useDebounce hook

---

.github/workflows/ci.yml

Yarn cache 적용

---

components/index/TodoListItem/index.tsx

MOZI-118
MOZI-119
MOZI-120
https://user-images.githubusercontent.com/51700274/180655025-9ac8e0ee-f452-4740-85a3-07154464cda1.mov
모든 버그 수정하였습니다 :)

fix: todo update 버그 수정

---

components/index/TodoList/index.test.tsx
components/index/TodoListItem/index.test.tsx
components/index/TodoListItem/index.tsx
components/index/TodoListItem/styles.tsx

TodoListItem 컴포넌트 리팩터링
https://user-images.githubusercontent.com/63354527/180774096-b6b8351b-f91d-42f2-8b58-74c9ac20c7cb.mov

refactor: TodoListItem 컴포넌트

---

components/index/TodoListItem/index.tsx
hooks/useDebounce/index.test.ts
shared/types/service-worker.d.ts
worker/index.ts

refactor: TodoListItem  컴포넌트

---

hooks/useMap.ts
pages/map/index.tsx
shared/utils/getCurrentPosition.ts

네이버 지도에 사용자 위치 마킹
저는 지금 정보화본부에 있습니다 ^^

feat: 사용자 위치 마킹

---

components/index/TodoList/index.test.tsx
components/index/TodoSubmitForm/index.test.tsx
pages/index.tsx

test: TodoSubmitForm 컴포넌트 테스트 코드 추가

---

hooks/apis/todo/useTodoListQuery.ts
pages/index.tsx
shared/types/common.ts

useTodoListQuery를 만들고 이를 활용해 MainPage를 리팩터링

feat: useTodoListQuery

---

components/index/TodoListItem/index.tsx
components/index/TodoListItem/styles.tsx
hooks/useOnClickOutside/index.test.ts
hooks/useOnClickOutside/index.ts
pages/_app.tsx
services/apis/todo.ts

- #113
https://user-images.githubusercontent.com/51700274/182154874-9c60b173-a670-4a5f-a9c7-ed92c08c545a.mov
- 지금 컴포넌트 네이밍이 너무 구립니다... Title 이라고 하는 컴포넌트가 이름만 봐서는 정확히 어떤 컴포넌트인지 파악이 안될 것 같은데 이름 추천 받아요
- onOutsideClick 훅이 있는데 생각해보니까 이름이 onClickOutside가 맞지 않나... 해서 바꿨습니다.

feat: 장소를 입력받기 위해 Todo 클릭시 공간 늘어나는 기능 구현

---

components/index/MapModal/index.tsx
components/index/MapModal/styles.tsx
components/index/TodoListItem/index.tsx
components/index/TodoListItem/styles.tsx
hooks/useMap.ts
pages/_app.tsx
pages/map/index.tsx

- #114
- 장소 입력을 받기위한 지도 모달 띄우기 기능 구현
https://user-images.githubusercontent.com/51700274/182292156-b380d4e2-86e0-4f2c-93c3-1640208003a6.mov
- 스타일은 안먹였습니다... ㅎ;

feat: Todo 클릭시 지도 띄우기

---

hooks/useLocalForage/index.test.ts
hooks/useLocalForage/index.ts
package.json
yarn.lock

feat: useLocalForage

---

components/index/TodoListItem/index.tsx
components/index/TodoListItem/styles.tsx
shared/types/todo.ts

style: TodoListItem 하위 컴포넌트 네이밍 개선

---

components/index/MapModal/index.tsx
components/index/MapModal/styles.tsx
components/index/TodoList/index.tsx
components/index/TodoListItem/index.tsx
components/map/SearchInput/index.tsx
hooks/apis/todo/useTodoMutation.ts
hooks/useMap.ts
pages/_app.tsx
pages/index.tsx
services/apis/todo.ts
shared/types/todo.ts
worker/index.ts

#115 
- 지도에 체크버튼 플러스 버튼 추가
- 체크버튼 클릭시 현재 마커 위치로 투두 위치 업데이트
비디오가 너무 크다고 하네요...

feat: 지도에서 장소데이터 업데이트

---

worker/index.ts

feat: cache data using service worker

---

pages/_app.tsx
services/apis/webpush.ts
shared/types/window.d.ts
shared/utils/encryption.ts
worker/index.ts

MOZI-147
MOZI-149
#138 
- 서비스 워커 구독
- 알림 요청 로직 모듈화
콘솔에 오류가 찍히는데 알림을 잘 오는걸 보면 ... 왜 뜨는지 잘 모르겠음
지라 & 이슈에 등록 예정

feature: web push 구독 및 알림 받기

---

components/index/MapModal/index.tsx
components/index/TodoList/index.tsx

MOZI-162
- 장소 업데이트가 잘 되지 않는 버그 수정
이제 잘 됩니다 :)

fix: 장소 업데이트가 제대로 이루어지지 않는 버그 수정

---

components/common/Sidebar/SideBarMenu/index.tsx
components/common/Sidebar/SideBarMenu/styles.tsx
components/common/Sidebar/styles.tsx
components/index/Header/index.test.tsx
components/index/Header/styles.tsx
pages/_app.tsx
pages/index.tsx
shared/utils/testUtils.tsx
styles/style.d.ts
styles/theme.ts

UI 개선, Darkmode 구현
https://user-images.githubusercontent.com/63354527/184080437-d1668217-7d01-42c0-8a29-7343295471f9.mov

feat: darkmode, toggle button 구현

---

components/common/AppLayout/index.tsx
components/common/AppLayout/styles.tsx
pages/_app.tsx
pages/index.tsx
shared/constants/breakpoints.ts
shared/utils/fetcher.ts
store/sidebar/atom.ts

기존 구조에서 AppLayout을 만들고 거기에 SideBar를 위치시켰습니다.

feat: sidebar 컴포넌트 _app에 적용 (모든 페이지)

---

.github/workflows/lighthouse.yml
.gitignore
.lighthouserc.js

feat: lighthouse ci 적용

---

.github/workflows/ci.yml

fix: push -> ci 실행하도록 변경

---

.github/workflows/lighthouse.yml

develop branch에서만 ci가 실패하는 버그 수정

fix: develop branch에서 ci 실패

---

.github/workflows/lighthouse.yml

lighthouse 결과 반환 -> parsing -> 댓글로 추가
진짜 한 50번정도 한 것 같다.

feat: install lighthouse app

---

.gitignore
components/common/Figure/CALENDAR.tsx
components/common/Figure/DEADLINE.tsx
components/common/Figure/PLACE.tsx
components/common/Figure/TAG.tsx
components/index/MapModal/index.tsx
components/index/TodoList/index.test.tsx
components/index/TodoList/index.tsx
components/index/TodoListItem/index.stories.tsx
components/index/TodoListItem/index.test.tsx
components/index/TodoListItem/index.tsx
pages/_app.tsx
pages/index.tsx
services/apis/todo.ts
shared/constants/sync.ts
shared/types/todo.ts
shared/utils/fetcher.ts
shared/utils/sync.ts
worker/index.ts

#165 
service-worker, SyncManager를 사용한 오프라인 동기화 구현
- 회의에서 데모.
[스택오버플로우 질문](https://stackoverflow.com/questions/71349128/where-to-put-periodic-background-sync-in-next-js-pwa) 
위 질문에 따르면, 크롬 및  Chromium-based browsers에서 백그라운드 동기화는 설치된 PWA에 한하여 동작한다.

feat: TodoListItem 성능 최적화 및 오프라인 동기화 구현

---

components/common/Button/index.stories.tsx
components/common/Button/index.tsx
components/common/Button/styles.tsx
components/index/Header/index.tsx
components/index/Header/styles.tsx
shared/types/style.d.ts
styles/theme.ts

style: 메모 추가 버튼

---

components/index/MapModal/index.tsx
components/index/TodoList/index.test.tsx
components/index/TodoList/index.tsx
components/index/TodoListItem/index.stories.tsx
components/index/TodoListItem/index.tsx
pages/index.tsx
services/apis/alarm.ts
services/apis/todo.ts
shared/types/location.ts
shared/types/todo.ts
shared/utils/encryption.ts
shared/utils/fetcher.ts
shared/utils/serialize.ts
worker/index.ts

오프라인 기능과 겹쳐 발생한 버그 수정하였습니다.
- 
용량이 커서 카카오톡으로 공유하였습니다.

feat: 장소에 따라 알림 (#179)

---

components/index/MapModal/index.tsx
components/index/MapModal/styles.tsx
components/index/TodoListItem/index.test.tsx
components/index/TodoListItem/index.tsx
components/index/TodoListItem/styles.tsx

MOZI-180
- todo box 스타일링
- 더블클릭이 되지 않은 상태에서 todo title을 수정할 수 있는 버그 수정
- 한번 클릭시 테두리가 생기면서 포커스 상태 볼 수 있도록 수정
- 더블클릭시 나타났던 기존의 테두리 대신 shadow로 더블클릭 상태 인지 할 수 있도록 수정
- title 및 description 포커스 시 나타났던 outline 없앰
- todo 안의 지도에서 사용하지 않는 확대 버튼 삭제
- todo 안의 지도에서 장소를 확정하는데 사용하는 버튼 스타일링
https://user-images.githubusercontent.com/51700274/186068041-56f6eb91-663b-422c-a6b1-3798c5331f83.mov
MOZI가 이뻐졌습니다 :)

style: todo 컴포넌트 UI 스타일링

---

components/common/Sidebar/styles.tsx
components/index/TodoListItem/index.tsx
components/index/TodoListItem/styles.tsx

스타일에 맞게 삭제버튼을 없애고 backspace 버튼이나 delete 버튼으로 todo를 삭제 가능하도록 구현
함께 #192 버그도 수정하였습니다.
https://user-images.githubusercontent.com/51700274/186078722-5c066fab-ed0b-4018-989c-57d48dbbcc74.mov

refactor: backspace or delete 버튼으로 todo 삭제

---

components/index/Title/index.tsx
components/index/Title/styles.tsx

style: inbox title

---

components/common/Figure/CALENDAR.tsx
components/common/Figure/FOOTERCALENDAR.tsx
components/common/Figure/index.tsx
components/common/Footer/index.tsx
components/index/TodoListItem/index.tsx
public/assets/svgs/calendar.svg
public/assets/svgs/footer_calendar.svg

fix: figure calendar 이름 겹치는거 이름 수정

---

components/common/Sidebar/SideBarMenu/index.tsx
components/common/Sidebar/index.tsx
components/common/Sidebar/styles.tsx
pages/index.tsx
store/todo/atom.ts

사이드바에 뜨는 Todo와 Todolist 개수의 동기화

feat: todo 개수 sidebar에 표시

---

components/map/SearchInput/index.tsx
components/map/SearchInput/styles.tsx
pages/map/index.tsx

map의 searchbar을 열고 닫는 기능을 구현했습니다.
https://user-images.githubusercontent.com/63354527/187200748-61ef0f75-4bc7-4aef-9cea-b9149cc25eae.mov

feat: map searchbar 열고 닫는 기능 구현

---

components/map/RecentSearch/index.tsx
components/map/RecentSearch/styles.tsx
components/map/SearchSideBar/index.tsx
components/map/SearchSideBar/styles.tsx
pages/map/index.tsx
styles/theme.ts

style: map 페이지 최근 검색어 UI

---

components/common/Figure/index.tsx
components/common/Sidebar/index.tsx
components/map/SearchSideBar/index.tsx
components/map/SearchSideBar/styles.tsx
pages/map/index.tsx
shared/utils/map.ts

지도에서 검색기능을 구현했습니다. 
근데지금 장소검색이 구,동,시 (예: 대전광역시)만 검색 가능하고 스타벅스 이런거 검색하면 안나오는데 naver api중에 다른 검색 API를 써야할 것 같습니다. 이 부분은 API 요청하는 부분만 바꾸면되서 일단 이렇게 푸시합니다.

feat: 지도에서 검색 기능 구현

---

components/map/SearchSideBar/index.tsx
services/apis/location.ts
shared/utils/location.ts
shared/utils/map.ts

MOZI-184
- api 받아와서 드롭다운 리스트로 결과값 보여주기
- 현재 위치 받는 함수 리팩토링

feat: get nearbysearch list in map page

---

pages/index.tsx

feat: 할 일 추가시 위에서 부터 추가

---

components/index/TodoList/index.test.tsx
components/index/TodoListItem/index.test.tsx
components/index/TodoListItem/index.tsx
components/index/TodoListItem/styles.tsx
public/assets/svgs/check.svg
shared/types/style.d.ts
styles/theme.ts

style: TodoListItem 스타일링 

---

shared/utils/debounce/index.test.ts
shared/utils/debounce/index.ts

feat: debounce function

---

components/index/TodoListItem/index.tsx
pages/index.tsx

더블 클릭하고 해제시 Description 렌더링 안되는 버그 해결

fix: 더블 클릭시 Description 렌더링 안되는 버그

---

components/trash/Title/index.tsx
components/trash/Title/styles.tsx

feat: Trash 페이지 비우는 버튼

---

components/index/TodoListItem/index.tsx
components/index/TodoListItem/styles.tsx
components/trash/Title/styles.tsx
components/trash/TodoList/index.tsx
components/trash/TodoList/styles.tsx
components/trash/TodoListItem/index.tsx
components/trash/TodoListItem/styles.tsx
hooks/useInputRef.ts
package.json
pages/trash/index.tsx
services/apis/todo.ts
yarn.lock

MOZI-207
TodoListItem의 칩들과 애니메이션 효과는 다른 pr로 나누어서 올리도록하겠습니다. (RFC 작성해서 pr 하나로 묶을 예정)

feat: Trash 페이지에 새로운 TodoListItem 컴포넌트 제작

---

middleware.ts
package.json
pages/_app.tsx
pages/kakao/index.tsx
shared/utils/cookie.ts
shared/utils/fetcher.ts
yarn.lock

feat: cookie를 활용한 login page로의 redirection

---

components/trash/Title/index.tsx
hooks/apis/todo/useTodoMutation.ts
pages/trash/index.tsx
services/apis/todo.ts

휴지통에서 Empty 버튼을 누를시 휴지통을 비웁니다.

feat: 휴지통 비우기 기능 추가

---

components/trash/TodoList/index.tsx
components/trash/TodoListItem/index.tsx
components/trash/TodoListItem/styles.tsx

MOZI-196
https://user-images.githubusercontent.com/63354527/190834437-dfb881da-311a-4211-81ea-5c9887888d58.mov

feat: 방향키로 TodoListItem의 focused 상태를 변경할 수 있도록 변경

---

worker/index.ts

MOZI-221 
캐시 용량을 더 줄 일 수 있을 것 같습니다.

fix: naver, kakao 관련 js 파일 캐시하지 않도록 변경

---

pages/kakao/index.tsx
shared/utils/kakao.ts

production 환경에서 kakao로그인이 작동하도록 server url을 추가해줍니다.

chore: kakao login production url 수정

---

pages/kakao/index.tsx

서버에서 준 jwt 토큰을 브라우저에서 쿠키로 저장
JWT를 정확히 활용하는 것은 쉽지 않은 것 같다. AccessToken과 RefreshToken 발급등의 공부가 필요할듯함.

fix: cookie 저장 방법 수정

---

components/index/TodoListItem/index.tsx
components/index/TodoListItem/styles.tsx

MOZI-197
TodoListItem이 250줄가량되는데 이를 더 작은 컴포넌트로 나누는 작업을 해야합니다.

feat: Todo focusing 상태에서 Enter 누르면 열리도록 변경

---

README.md

readme에 다음과 같은 내용을 추가했습니다.
- 서비스 소개
- 기술 스택
- 개발자 및 프로젝트에 도움을 주신 분들

docs: readme 내용 추가 (서비스 소개, 기술 스택, 개발자 및 프로젝트에 도움을 주신 분들)

---

components/map/SearchSideBar/index.tsx
components/map/SearchSideBar/styles.tsx
hooks/useNaverMap.ts
pages/map/index.tsx

feat: 검색 결과를 클릭하면 지도의 중앙이 결과로 이동하고 마킹 표시를 한다.

---

docker-compose.yml

fix: docker compose 환경변수 설정

---

components/map/SearchSideBar/RecentSearch/index.tsx
components/map/SearchSideBar/index.tsx

feat: 최근 검색어를 클릭해도 지도에서 이동할 수 있다.

---

src/components/common/TodoListItem/index.tsx
src/hooks/apis/todo/useTodoListQuery.ts
src/hooks/apis/todo/useTodoMutation.ts
src/services/apis/todo.ts

MOZI-257
https://user-images.githubusercontent.com/63354527/192199607-9fd82c4e-9750-4517-8e7c-d186d4530920.mov

feat: inbox에서 done이 아닌 항목만 출력

---

src/hooks/apis/todo/useTodoListQuery.ts
src/pages/map/index.tsx
src/shared/types/todo.ts

feat: map에 사용자가 등록한 TodoList 보여주기

---

package.json
src/components/common/ModalBackground/index.tsx
src/components/common/ModalBackground/styles.tsx
src/components/common/Portal/index.tsx
src/components/common/SetLocationModal/index.tsx
src/components/common/SetLocationModal/styles.tsx
src/components/common/Sidebar/index.tsx
src/components/common/TodoListItem/Map/index.tsx
src/components/common/TodoListItem/index.tsx
src/components/map/SearchSideBar/index.tsx
src/hooks/apis/todo/useTodoMutation.ts
src/hooks/useOnClickOutside/index.test.ts
src/hooks/useOnClickOutside/index.ts
src/pages/_document.tsx
src/services/apis/todo.ts
src/shared/types/todo.ts
yarn.lock

- 모달 컴포넌트에 이벤트 등록
- 모달 배경 이벤트 관련 버그 수정
- 모달에서 장소 이름 입력 받고 데이터 베이스 업데이트 요청
잘 업데이트 되는 모습입니당..ㅎㅎ
찬희님이 하신거를 잘못 닫아서 다시 올립니다..

feat: 장소이름 입력받는 모달 기능 구현

---

src/components/common/AlertModal/index.stories.tsx
src/components/common/AlertModal/index.tsx
src/components/common/AlertModal/styles.tsx
src/components/common/Chip/index.tsx
src/components/common/SetLocationModal/index.tsx
src/components/common/TodoListItem/Map/index.tsx
src/components/common/TodoListItem/Options/index.tsx
src/components/common/TodoListItem/index.tsx
src/shared/types/todo.ts

모달을 이용한 등록된 장소 삭제하는 기능
- 취소 모달창 구현
- 등록된 장소 삭제 요청
- Chip에서 이벤트 버블링으로 인한 버그 수정
- Chip의 delete 버튼의 유무와 지도의 유무에 대한 통일성을 위해 장소 등록을 하면 지도가 닫히게 수정
- 처음 Chip 클릭시 delete 버튼 나옴
- X 버튼 클릭시 모달 발생
- 확인 (삭제) 버튼 클릭시 장소 데이터 삭제

feat: 등록된 장소 삭제

---

public/assets/svgs/cancel.svg
src/components/common/Figure/CANCEL.tsx
src/components/common/Figure/index.tsx
src/components/map/SearchSideBar/RecentSearch/index.tsx
src/components/map/SearchSideBar/RecentSearch/styles.tsx
src/components/map/SearchSideBar/index.tsx
src/components/map/SearchSideBar/styles.tsx

MOZI-246
https://user-images.githubusercontent.com/63354527/193318937-258acdf5-500a-40cf-9bc9-668267d15cd8.mov
이번주 스프린트는 이걸로 끝..

feat: 최근 검색어 삭제 기능

---

README.md

docs: 모지 공식문서 사이트 추가

---

package.json
public/assets/svgs/next_arrow.svg
public/assets/svgs/prev_arrow.svg
src/components/common/CalendarModal/index.stories.tsx
src/components/common/CalendarModal/inedex.tsx
src/components/common/CalendarModal/styles.tsx
src/components/common/Figure/NEXTARROW.tsx
src/components/common/Figure/PREVARROW.tsx
src/components/common/Figure/index.tsx
src/hooks/apis/todo/useTodoListQuery.ts
src/shared/types/todo.ts
src/shared/utils/date.ts
src/shared/utils/dateToString.ts
yarn.lock

캘린더 모달 구현했습니다.
- 캘린더 모달 디자인 구현
- 내부 날짜 클릭시 이벤트 구현
- 위쪽 화살표 클릭시 이벤트 구현
https://user-images.githubusercontent.com/51700274/193443597-3d816b1c-e32f-4f69-af0a-bf80537c78ee.mov
추가로 로그북이랑 맵쪽에 있던 버그도 수정했습니당 :)

feat: 캘린더 모달 구현

---

src/components/common/TodoListItem/Map/index.tsx
src/components/trash/Title/styles.tsx
src/hooks/useNaverMap.ts

useNaverMap에서 발생하는 sideEffect 제거
useNaverMap에서 사용자의 위치를 찍는 것이 아닌 그 훅을 사용하는 곳에서 마커를 찍습니다. 이렇게함으로써 sideEffect를 제거했습니다.

fix: useNaverMap side effect 제거

---

src/components/common/TodoListItem/Map/index.tsx
src/components/common/TodoListItem/Options/index.tsx
src/hooks/useNaverMap.ts
src/pages/map/index.tsx

useNaverMap의 남은 사이드 이펙트 제거 및 찬희가 만든 기능 정상 동작 (스타일링 제외)

refactor: useNaverMap hook

---

.env
src/components/common/TodoListItem/index.tsx
src/pages/_app.tsx

MOZI-297
useCallback의 의존 배열 때문이었다는 슬픈 사실

fix: Inbox 항목을 많이 추가 후 맨 아래 할일 클릭시 하이라이트 안되는 버그

---

package.json
src/components/common/TextInput/index.stories.tsx
src/components/common/TextInput/index.test.tsx
src/components/common/TextInput/index.tsx
src/components/common/TextInput/styles.tsx
src/components/map/SetLocationModal/index.tsx
src/shared/constants/input.ts
yarn.lock

feat: common text input component

---

src/components/common/TextInput/index.tsx
src/components/map/SetLocationModal/index.tsx
src/hooks/useInput.ts

기존 useState사용에서 useInput 훅을 사용해 input의 attribute를 가져와 그 글자이상이되면 타이핑이 안되도록 조정합니다.

refactor: useInput 훅을 사용한 글자 제한

---

src/components/common/Sidebar/SideBarMenu/index.tsx
src/components/common/Sidebar/index.tsx
src/hooks/apis/todo/useTodoListQuery.ts
src/hooks/apis/todo/useTodoMutation.ts
src/shared/types/todo.ts

MOZI-296
https://user-images.githubusercontent.com/63354527/193990911-2d46a5b8-7fc5-4b1f-a73b-4fa8cf05c219.mov
기능이 동작하도록 코딩했습니다. 리액트 쿼리의 타입들과 쿼리 키를 어떻게 할것인지는 공부를 해보겠습니다.

feat: 사용자는 사이드바에서 Todo의 개수를 파악할 수 있다.

---

src/components/common/CalendarModal/index.tsx
src/components/common/TodoList/index.tsx
src/components/common/TodoListItem/Options/index.tsx
src/components/common/TodoListItem/index.tsx
src/hooks/apis/todo/useTodoMutation.ts
src/services/apis/todo.ts
src/shared/types/todo.ts
src/shared/utils/date.ts

백엔드에 해당 데이터에 대해 요청을 보낼수 있도록 구현하였습니다.
해당 부분 구현에 따라 todo list item에 기본적으로 표현 되어야할 아이콘들도 보일 수 있도록 구현하였습니다.
- 백엔드 요청 로직 (패러미터 due date, alarm date 추가) 변경
- todo list item에 due date, alarm date가 있는 경우 표시
닫혀있는 투두
열려있는 투두
장소와 같이 있는 경우
due date나 alarm date 삭제에 대한 부분은 아직 구현을 하지 않았습니다.
시간에 따른 알림 기능도 구현하지 않았습니다.

feature: due date, alarm date 백엔드에 요청 보내기 구현

---

src/hooks/apis/todo/useTodoMutation.ts
src/pages/trash/index.tsx
src/services/apis/todo.ts

feat: force delete Todo

---

src/components/TestComponent.tsx
src/components/common/TodoListItem/index.tsx

키보드 이벤트에서 조건을 제대로 주지 않아서 발생하는 버그 해결

fix: 장소 입력 안되는 버그

---

src/hooks/useDoubleTap/index.test.tsx
src/hooks/useDoubleTap/index.ts

feat: useDoubleTap hook

---

src/components/upcoming/Calendar/index.tsx
src/components/upcoming/Calendar/styles.tsx
src/components/upcoming/Title/index.tsx
src/hooks/apis/todo/useTodoMutation.ts
src/pages/upcoming/index.tsx

캘린더 컴포넌트 구현하였습니다.
다른 기능은 없습니다.
날짜 이동은 가능합니다 :)
- Upcomming에 들어갈 캘린더 컴포넌트 구현

feat: Upcomming 페이지 캘린더 컴포넌트 구현

---

next.config.js

sentry 설정에 의해 service worker 등록 되지 않는 버그 수정

fix: service worker registration by sentry

---

src/pages/kakao/index.tsx

style: 카카오 로그인 대기화면에서 로딩 스피너 가운데로 배치

---

.storybook/preview.js
src/components/common/Button/index.stories.tsx
src/components/common/Button/index.tsx
src/components/common/Button/styles.tsx
src/components/common/Spinner/index.stories.tsx

feat: Common Button Component

---

src/components/common/Button/index.tsx
src/components/common/Button/styles.tsx
src/components/setting/LogoutButton/index.tsx
src/pages/setting/index.tsx
src/shared/utils/cookie.ts

https://user-images.githubusercontent.com/63354527/195966482-2b135bac-e316-4485-928a-dc68303a05e6.mov

feat: logout

---

src/components/common/TodoListItem/index.tsx
src/components/common/TodoListItem/styles.tsx
src/pages/index.tsx

DND로 할 일 삭제 기능 (기능만 개발 서버에 api 요청 X)
https://user-images.githubusercontent.com/63354527/195976162-772bc144-13e9-42d0-bf19-e97ba5d5d810.mov

feat: DND를 활용한 할 일 삭제 

---

src/components/common/Chip/index.stories.tsx
src/components/common/DropPlaceholder/index.stories.tsx
src/components/common/DropPlaceholder/index.tsx
src/components/common/DropPlaceholder/styles.tsx
src/pages/index.tsx

feat: drop placeholder 공통 컴포넌트

---

src/components/common/AppLayout/index.tsx
src/components/common/Sidebar/index.tsx
src/components/common/Title/styles.tsx

refactor: sidebar에서 data fetching로직 상위 컴포넌트로 이동

---

package.json
src/components/common/Profile/index.stories.tsx
src/components/common/Profile/index.tsx
src/components/common/Profile/styles.tsx
src/components/common/Sidebar/index.tsx
src/components/common/Sidebar/styles.tsx

feat: Profile 공통 컴포넌트

---

src/components/common/CalendarModal/index.tsx
src/components/upcoming/Calendar/index.tsx
src/services/apis/todo.ts
src/shared/utils/date.ts
src/worker/index.ts

시간에 따라 푸시알림이 올 수 있도록 구현하였습니다.
- 알림 시간에 맞춰 푸시 알림 기능 구현
- 서비스 워커에서 푸시 알림을 위한 subscription이 등록이 잘 안되는 버그 수정
- 캘린더 모달에서 시간, 분 정보가 정확히 업데이트가 안되는 버그 수정
장소와 시간은 and 조건입니다.
장소가 없는 경우: 시간만 체크
시간이 없는 경우: 장소만 체크
둘다 있는 경우: and조건으로 둘 다 체크

feat: 시간에 따른 푸시 알림 기능 구현

---

src/hooks/apis/todo/useTodoMutation.ts
src/pages/index.tsx
src/pages/map/index.tsx
src/services/apis/todo.ts
src/shared/types/todo.ts

- 맵 클릭시 장소 이름 모달 발생
- 장소 이름 적고 확인 누르면 해당 위치로 장소가 찍힌 todo 생성
- 장소와 함께 create해주기 위한 서비스 로직 수정
https://user-images.githubusercontent.com/51700274/196431801-d60db779-4c97-4089-aabc-e3fb61addbe2.mov

feat: map 페이지에서 Todo 추가 기능 구현

---

src/hooks/apis/todo/useTodoListQuery.ts
src/worker/cache.ts
src/worker/index.ts

refacotor: caching 로직 분리

---

src/shared/utils/serviceWorker.ts
src/shared/utils/sync.ts

feat: serviceworker에 관한 util 함수 작성 및 모듈화

---

src/hooks/apis/todo/useTodoListQuery.ts
src/hooks/apis/todo/useTodoMutation.ts
src/pages/index.tsx
src/services/apis/todo.ts
src/shared/utils/serviceWorker.ts

feat: use_unsafe_createTodo

---

src/hooks/apis/todo/useTodoMutation.ts
src/pages/index.tsx
src/services/apis/todo.ts

feat: use_unsafe_updateTodo

---

src/components/common/TodoList/DraggableTodoList.tsx
src/components/common/TodoListItem/index.tsx
src/components/map/SearchSideBar/index.tsx
src/hooks/apis/todo/useTodoListQuery.ts
src/hooks/apis/todo/useTodoMutation.ts
src/pages/index.tsx
src/services/apis/todo.ts
src/shared/constants/serviceWorker.ts
src/shared/constants/sync.ts
src/shared/utils/serviceWorker.ts
src/shared/utils/sync.ts
src/worker/index.ts

1. 처음에 투두를 받아온다. 이 때 Sync 이벤트와는 관계가 없다. 그냥 Todo를 불러오고 IndexedDB에 저장하며 그걸 불러와야한다.
2. 반면에 업데이트 하거나 삭제하는 것은 다르다. 즉, 업데이트할 때는 IndexedDB가 업데이트가 완료되면 Sync이벤트를 등록해줘야한다. 
3. 할 일을 추가하는 것또한 Sync 이벤트가 등록되어야한다.

feat: sync 이벤트를 사용해 IndexedDB에서 DB로 데이터 동기화

---

src/components/common/Header/index.stories.tsx
src/components/common/Header/styles.tsx
src/components/common/Title/styles.tsx
src/pages/index.tsx
src/pages/logbook/index.tsx
src/pages/map/index.tsx
src/pages/trash/index.tsx
src/pages/upcoming/index.tsx
src/styles/theme.ts

style: header 스타일링 및 적용해야할 페이지에 적용

---

src/hooks/apis/todo/useTodoMutation.ts
src/pages/index.tsx
src/services/apis/todo.ts
src/shared/constants/dialog.ts
src/shared/types/todo.ts
src/shared/utils/serviceWorker.ts

https://user-images.githubusercontent.com/63354527/197336348-882d1446-c3ce-4c29-9e49-9629b5b4a3ba.mov

feat: Drag And Drop을 통해 Todo의 index를 바꿀 수 있다.

---

public/manifest.json
src/styles/globalStyle.ts

pwa display mode를 production 환경에서 test

feet: display fullscreen mode 테스트

---

public/manifest.json
src/components/common/SEO/index.tsx
src/pages/_app.tsx
src/pages/_document.tsx
src/shared/constants/application.ts

refactor: SEO Component

---

src/components/common/DropPlaceholder/styles.tsx

fix: dropplaceholder absolute 속성줘서 감추기

---

src/components/common/Sidebar/index.tsx

fix: sidebar에서inbox에 제대로 focus되지 않는 부분 수정

---

src/components/common/TodoListItem/Title/index.stories.tsx
src/components/common/TodoListItem/Title/index.tsx
src/components/common/TodoListItem/Title/styles.tsx
src/components/common/TodoListItem/index.stories.tsx
src/components/common/TodoListItem/temp.tsx
src/pages/_app.tsx
src/pages/_document.tsx

refactor: TodoListItem Title Component

---

src/components/common/TodoList/styles.tsx
src/components/common/TodoListItem/Description/index.stories.tsx
src/components/common/TodoListItem/Description/index.tsx
src/components/common/TodoListItem/Description/styles.tsx
src/components/common/TodoListItem/Title/index.tsx
src/components/common/TodoListItem/Title/styles.tsx
src/components/common/TodoListItem/index.tsx
src/components/common/TodoListItem/styles.tsx

refactor: TodoListItem Description Component

---

src/components/map/SearchSideBar/MapTodoList/index.tsx
src/components/map/SearchSideBar/MapTodoList/styles.tsx
src/components/map/SearchSideBar/index.tsx
src/hooks/useNaverMap.ts
src/pages/map/index.tsx

맵 페이지 사이드바에 지도 내부에 있는 Todo 보이는 기능 구현
- Map에서 사용할 Todo list 컴포넌트 구현
- 지도의 경계 구하는 로직 구현
https://user-images.githubusercontent.com/51700274/197820827-b157252c-6f8e-4838-b087-31dc4a163f94.mov

feat: 맵 페이지 사이드바에 지도 내부에 있는 Todo 보이는 기능 구현

---

src/hooks/useNaverMap.ts
src/pages/map/index.tsx

멘토링에서 언급한 대로 naverMap의 bounds 부분을 map page로 나누었습니다.
동작하는 기능을 동일 합니다.

refactor: 다른 navermap hook에서 안쓰이는 부분 나누기

---

src/components/common/Header/styles.tsx
src/components/common/Title/styles.tsx
src/components/common/TodoListItem/styles.tsx
src/shared/types/style.d.ts
src/styles/theme.ts

style: Title및 TodoListItem Background Dark Mode 적용

---

src/pages/map/index.tsx

마커 핀을 클릭하면 해당 Todo의 Title 확인하는 기능
Title이 비어있다면 Toast 팝업을 띄우게 구현
- 마커 클릭시 title 보이게 구현
- 마커 클릭한 상태로 Todo를 고치면 업데이트가 안되는 버그 수정
- 비어있는 Title인 마커를 클릭하면 토스트로 경고가 발생하게 구현
- 클릭한 마커가 위로 올라오게 구현

feat: 마커 핀을 클릭하면 해당 Todo의 Title 확인하는 기능

---

src/components/common/TodoList/DraggableTodoList.tsx
src/components/common/TodoListItem/index.tsx
src/pages/upcoming/index.tsx
src/shared/types/todo.ts

fix: 지도를 드래그할 때 TodoListItem 까지 같이 드래그되는 버그 수정

---

src/pages/logbook/index.tsx
src/pages/map/index.tsx
src/pages/setting/index.tsx
src/pages/trash/index.tsx
src/pages/upcoming/index.tsx

https://user-images.githubusercontent.com/63354527/198502101-18abf664-f2fc-4535-a75c-c69dce24d38c.mov

style: 모든 페이지 백그라운드에 Darkmode transition 효과 적용

---

src/components/common/TodoList/index.tsx
src/hooks/apis/todo/useTodoListQuery.ts
src/hooks/apis/todo/useTodoMutation.ts
src/pages/upcoming/index.tsx
src/services/apis/todo.ts
src/shared/types/todo.ts
src/worker/index.ts

feat: 휴지통 비우기 기능 (sync with serviceWorker)

---

src/components/common/CalendarModal/index.tsx
src/components/common/DeleteModal/index.tsx
src/components/common/TodoList/DraggableTodoList.tsx
src/components/common/TodoList/index.tsx
src/components/common/TodoListItem/Description/index.tsx
src/components/common/TodoListItem/Map/index.tsx
src/components/common/TodoListItem/Options/index.tsx
src/components/common/TodoListItem/Title/index.tsx
src/components/common/TodoListItem/index.tsx
src/components/common/TodoListItem/unsafe_TodoListItem.tsx
src/components/map/SearchSideBar/MapTodoList/index.tsx
src/components/map/SearchSideBar/index.tsx
src/hooks/apis/todo/useTodoMutation.ts
src/pages/logbook/index.tsx
src/pages/map/index.tsx
src/pages/trash/index.tsx
src/services/apis/todo.ts

-> 우선 Inbox에만 적용된 상태 : React Query에서 타입정의를 하고 다른 페이지를 해야할 것 같음 (이렇게 안하면 다 찾아다니면서 타입 다바꿔줘야함)
IndexedDB에 
- title 잘써지는거 확인
- description잘써지는거확인
- 지도 마킹 잘되는것 확인
- Option 잘 들어가는 것 확인
⭐️BREAKING CHANGES⭐️

refactor(!): react-query 

---

src/components/common/DeleteModal/index.tsx
src/components/common/Footer/index.tsx
src/components/common/Modal/index.tsx

https://velog.io/@hyunjine/React-Rendering-Optimization

refactor: delete unnecessary useCallback

---

src/hooks/apis/todo/useTodoListQuery.ts
src/shared/constants/routes.ts

refactor: useTodoListQuery

---

src/hooks/apis/todo/useTodoMutation.ts
src/services/apis/todo.ts

sync를 사용한 Todo 복구 기능 잘 돌아가도록 구현하였습니다.

fix: sync를 사용한 Todo 복구

---

src/hooks/apis/todo/useTodoMutation.ts
src/services/apis/todo.ts
src/worker/index.ts

map page에서 Todo를 만들면 title이 안들어가는 버그 수정하였습니다.

fix: map page에서 Todo를 만드는 경우 버그 수정

---

cypress/.eslintrc.json
cypress/support/commands.ts
cypress/support/index.ts
cypress/tsconfig.json
package.json
src/components/common/AppLayout/index.tsx
src/shared/constants/application.ts
tsconfig.json
yarn.lock

feat: Add Cypress Eslint Plugin

---

.github/workflows/cypress.yml
.gitignore
cypress.config.ts

feat: add cypress ci

---

src/pages/_app.tsx
src/shared/constants/delay.ts
src/shared/constants/serviceWorker.ts
src/worker/index.ts

5초에 한번 현재 사용자의 위치를 바탕으로 알림을 보내야하는 Todo가 있는지 확인하는 로직에서 장소가 바뀌는 경우, 그리고 1분에 한번(분이 바뀌면 그때마다) Todo를 확인하는 방식으로 불필요한 Todo 확인을 줄였습니다.

refactor: 장소가 바뀔때, 1분마다 Todo 체크

---

cypress.config.ts

fix: Cypress Login

---

src/hooks/apis/todo/useTodoListQuery.ts
src/hooks/apis/todo/useTodoMutation.ts
src/services/apis/todo.ts

chore: legacy service 제거

---

src/hooks/apis/todo/useTodoMutation.ts
src/pages/inbox/index.tsx
src/pages/logbook/index.tsx
src/pages/map/index.tsx
src/pages/trash/index.tsx
src/pages/upcoming/index.tsx
src/shared/types/todo.ts

refactor: TodoList Mutation

---

src/components/common/TodoListItem/Options/index.tsx
src/components/common/TodoListItem/index.tsx

refactor: checkbox image

---

src/components/common/Chip/index.tsx
src/components/common/SetLocationModal/index.tsx
src/components/map/SearchSideBar/index.tsx
src/pages/kakao/index.tsx
src/pages/trash/index.tsx

refactor: useCallback 제거

---

src/components/common/Skeleton/index.stories.tsx
src/components/common/Skeleton/index.tsx
src/components/common/Skeleton/styles.tsx
src/components/common/TodoListItem/index.tsx
src/components/common/index.tsx
src/pages/inbox/index.tsx
src/shared/utils/queryClient.ts
src/store/localForage/index.ts

feat: TodoListItem에 대한 Skeleton UI 추가

---

src/pages/index.tsx

chore: Login 페이지에서 SEO 컴포넌트 제거 후 OG 확인

---

cypress/e2e/login.spec.ts
cypress/support/commands.ts
cypress/support/e2e.ts

refactor: Cypress Login E2E test

---

cypress/e2e/inbox.spec.ts
cypress/fixtures/todos.json
src/components/common/Spinner/index.tsx
src/styles/globalStyle.ts

feat: Cypress E2E Test Inbox Page API Mocking

---

src/components/common/Footer/index.tsx
src/hooks/apis/todo/useTodoMutation.ts
src/pages/inbox/index.tsx
src/services/apis/todo.ts
src/shared/constants/dialog.ts
src/shared/types/todo.ts
src/shared/utils/toast.ts
src/store/localForage/index.ts
src/worker/index.ts

refactor: API, ServiceWorker Sync

---

src/components/common/TodoListItem/index.tsx
src/hooks/apis/todo/useTodoMutation.ts
src/pages/trash/index.tsx
src/services/apis/todo.ts
src/shared/types/todo.ts

refactor: update request

---

.github/workflows/ci.yml
src/hooks/apis/todo/useTodoListQuery.ts
src/hooks/apis/todo/useTodoMutation.ts
src/services/apis/todo.ts
src/shared/types/todo.ts

refactor: Mutation Types

---

public/robots.txt
src/components/common/CalendarModal/index.tsx
src/components/common/Figure/NEXTARROW.tsx
src/components/common/Figure/PREVARROW.tsx
src/components/common/Title/index.tsx
src/components/upcoming/Calendar/index.tsx
src/components/upcoming/CalendarBody/index.tsx
src/components/upcoming/CalendarBody/styles.tsx
src/components/upcoming/CalendarHeader/index.tsx
src/components/upcoming/CalendarHeader/styles.tsx
src/components/upcoming/Navigator/index.tsx
src/components/upcoming/Navigator/styles.tsx
src/pages/temp.tsx
src/pages/upcoming/index.tsx
src/shared/types/style.d.ts
src/shared/utils/date.ts
src/styles/theme.ts

refactor: Calendar

---

src/components/common/TodoList/DraggableTodoList.tsx
src/components/common/TodoListItem/index.tsx
src/pages/inbox/index.tsx

- inbox에서 delete하는 부분을 update처리

refactor: offline delete 

---

.env
.env.development
.env.production
src/pages/migrations/google.tsx
src/pages/setting/index.tsx

- google Calendar를 연동 해서 Todo를 불러오는 기능

feat: google calendar 연동

---

src/hooks/apis/todo/useTodoMutation.ts

fix: 휴지통 비우기시 클라이언트 상태 업데이트하지 못하는 버그 수정

---

public/manifest.json
src/pages/index.tsx

https://web.dev/maskable-icon-audit/?utm_source=lighthouse&utm_medium=devtools

chore: 웹 접근성 개선

---

public/assets/svgs/crosshairs.svg
src/components/common/Figure/CROSSHAIRS.tsx
src/components/common/Figure/index.tsx
src/components/map/SetLocationModal/index.tsx
src/pages/map/index.tsx
src/shared/types/style.d.ts
src/styles/theme.ts
src/styles/utils.ts

feat: 사용자는 Map 페이지에서 현재 위치로 이동할 수 있다.

---

src/pages/setting/index.tsx
src/shared/constants/dialog.ts

refactor: google calendar 동기화 에러처리

---

src/pages/map/index.tsx

style: map page boundary 색상 변경

---

src/components/common/CalendarModal/index.tsx
src/pages/_app.tsx
src/shared/utils/date.ts
src/worker/index.ts

알림을 주는 방식을 기존 브라우저 -> 서비스워커에서 서비스워커에서 바로 처리하는 방식으로 개선

refactor: 알림 주는 방식 개선

---

src/components/common/AlarmModal/index.tsx
src/components/common/AlarmModal/styles.tsx

feat: 알림 모달에서 버튼 클릭시 표시

---

src/shared/types/todo.ts
src/worker/alarm.ts

`src/worker/alarm.ts` 를 추가했습니다. 여기 있는 함수를 이용해서 각 `todo`와 현재 `state`를 비교해서 알림을 울려야하는지 확인할 수 있습니다.

feat: 알림이 울려야하는지 확인하는 기능

---

src/components/upcoming/CalendarBody/index.tsx
src/components/upcoming/CalendarBody/styles.tsx

refactor: alarm, deadline 정보 표시

---

src/pages/_app.tsx
src/shared/constants/serviceWorker.ts
src/worker/alarm.ts
src/worker/index.ts

feat: 알람 조건 체크 로직

---

src/components/common/AlarmModal/index.tsx
src/worker/index.ts

feat: 알림 권한 요청

---

src/worker/alarm.ts

`1, 5, 10` -> `1000, 5000, 10000`

fix: distance standard bug

---

src/components/common/AlarmModal/index.tsx
src/pages/map/index.tsx
src/shared/types/todo.ts

feat: distance type에 따라 바운더리 다르게 구현
