components/index/TodoList/index.test.tsx, components/index/TodoList/index.tsx, components/index/TodoListItem/index.tsx, components/index/TodoSubmitForm/index.tsx, hooks/apis/todo/useTodoMutation.ts, hooks/useInput.ts, jest.config.js, pages/index.tsx, services/apis/todo.ts, shared/types/todo.ts, utils/fetcher.ts
리액트 쿼리와 컴포넌트가 의존 관계가 생기면 컴포넌트를 테스트하기 어려워집니다. 또한 개별 컴포넌트가 요청을 보내는 로직과 연관된다는 것 자체가 스토리북을 만드는 것 또한 어렵게 합니다. 
컴포넌트는 컴포넌트스러워야합니다. 컴포넌트에 api 요청 코드를 분리함으로써 컴포넌트를 컴포넌트 답게(테스트, storybook이 용이) 사용할 수 있습니다.
=> refactor: 메인페이지 컴포넌트들 리액트 쿼리와 의존성 제거

hooks/useDebounce/index.test.tsx
- 기존값과 새값을 INITIAL_VALUE와 NEW_VALUE값을 사용하여 보다 쉽게
구분하도록 함
- renderHook의 props를 활용하여 rerender시 새로운 값을 인자로 설정
=> refactor: useDebounce 테스트 코드 가독성 향상

components/common/Sidebar/index.tsx, components/common/Sidebar/styles.tsx
sidebar 넓이가 바뀔 때마다 styled-component에 의해 클래스 추가되는 버그 수정
https://user-images.githubusercontent.com/63354527/181566238-5ba78e49-9ce3-45e0-acdf-9551a427c3b5.mov
원래 경고로 떴던 attrs로는 해결 할 수 없었습니다. styled-component가 클래스를 자꾸 추가해주는건 attrs가 해결해주진 못했습니다.
그래서 width속성을 인라인 style로 바꿨습니다.
=> fix:  SideBar 넓이가 바뀔 때마다 styled-component에 의해 클래스 추가되는 버그 수정

components/index/TodoListItem/index.tsx, hooks/location/useLocation.ts, hooks/location/useLocationRef.ts, hooks/useLocation.ts, hooks/useMap.ts, pages/_app.tsx, pages/map/index.tsx, shared/types/location.ts, shared/utils/getCurrentPosition.ts, shared/utils/getDistance.ts
- 사용자 근접 위치 확인 MOZI-82
-  알림 표시 MOZI-117
https://user-images.githubusercontent.com/51700274/181914123-9f87cb7d-8b57-46cd-be8f-1228a585e912.mov
일단은 _App 내부에 배열을 둬서 해당 부분으로 등록된 알람을 확인한다고 가정하고 구현해놨습니다.
추후에 indexedDB나 서버의 데이터와 비교하는 로직을 추가할 예정입니다.
_app에서 현재 사용자의 위치를 상태로 관리하면 매번 현재위치를 다시 받아올 때마다 모든 페이지가 렌더링이 다시 되어서 Ref를 사용하는 방식으로 진행하였습니다.
=> feature: 주기적으로 근접 장소 확인 및 알림

hooks/useOnClickOutside/index.test.ts, hooks/useOnClickOutside/index.ts
프로젝트를 진행하면서 해당 컴포넌트 바깥쪽이 클릭되거나 터치되어야 할 상황에 이 훅을 활용할 수 있습니다.
이름을 어떻게 지을까 하면서 다른 사람들이 지어놓은 이름을 참고했는데 `useOnClickOutside`가 적당한 것 같습니다.
ref에 관찰할 대상을 전달하고 ref 바깥쪽의 다른 것을 클릭하면 그 클릭을 감지하고 두번째 인자로 전달한 handler가 실행됩니다. 
```ts
import { RefObject, useEffect } from 'react';
type Handler = (event: MouseEvent | TouchEvent) => void;
export const useOnOutsideClick = <T extends HTMLElement = HTMLElement>(ref: RefObject<T>, handler: Handler) => {
useEffect(() => {
const listener = (event: MouseEvent | TouchEvent) => {
if (!ref.current || ref.current.contains(event.target as HTMLElement)) return;
handler(event);
};
document.addEventListener('mousedown', listener);
document.addEventListener('touchstart', listener);
return () => {
document.removeEventListener('mousedown', listener); …
```
=> feat: useOnClickOutside

components/index/TodoList/index.test.tsx, components/index/TodoList/index.tsx, components/index/TodoListItem/index.stories.tsx, components/index/TodoListItem/index.test.tsx, components/index/TodoListItem/index.tsx, hooks/apis/todo/useTodoMutation.ts, pages/index.tsx, services/apis/todo.ts, shared/types/todo.ts
- 서버의 Todo return type 수정에 따른 프론트엔드에서 Todo 타입 수정 (_id -> id)
- 토론한 결과 Todo Title, Todo Description...등 (Todo에서 사용자 입력을 받을 수 있는 모든것)을 상태로 관리
=> refactor: TodoListItem

components/index/TodoListItem/index.tsx, components/index/TodoListItem/styles.tsx
#122 
- https://stackoverflow.com/questions/49639144/why-does-react-warn-against-an-contenteditable-component-having-children-managed
- https://chaewonkong.github.io/posts/auto-width-text-input.html
=> feat: TodoListItem Description에 ContentEditable 적용

components/index/TodoList/index.tsx, shared/utils/localForage.ts
#134 
사용자는 네트워크가 불안정한 환경이나 오프라인에서도 자신의 할 일을 확인/편집하고 싶다.
https://user-images.githubusercontent.com/63354527/183272562-7c06d681-f363-4290-b58e-12e92e4901e7.mov
=> feat: TodoList가 업데이트 되면 자동으로 IndexedDB에 저장

services/apis/webpush.ts
api를 `POST .../api/v1/webpush/:id`로 바꿨기 때문에 `webpushService`도 바꿨습니다.
- api end point 변경
=> fix: notification api end point update

components/index/TodoListItem/index.tsx
esc 클릭시 title이나 description을 입력하고 있다면 포커스를 제거해준다. 
문제를 해결하기 위한 코딩을 했다. 개선의 여지는 있다. 
TodoListItem에 focus 상태를 만들어 TodoListItem이 focused 되어있다면 window에 등록된 eventListener가 처리해주는 것은 어떨까?
=> feat: ESC 클릭시 TodoListItem에서 포커스 제거

package.json, pages/_app.tsx, pages/api/auth/[...nextauth].ts, pages/login.tsx, shared/types/environment.d.ts, yarn.lock
카카오 로그인 구현. 
현재 로그아웃 로그인과 로그아웃만 되게끔 구현했고 login시에 정보를 MongoDB에 적는 작업을 추후 구현해야합니다. 
1. 로그인 성공 -> 만약 저장되어있는 아이디이면 mongodb에 적지 않음
2. 로그인 성공 -> 저장되어있는 아이디가 아니면 mongodb에 적음
=> feat: nextauth를 사용한 카카오 로그인 구현

components/common/Figure/ARROWLEFT.tsx, components/common/Figure/ARROWRIGHT.tsx
svg의 props를 react에 맞게 바꿨습니다.
```js
<SvgWrap>
<svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M3 8L10 15L3 22" stroke="#2A2A2A" strokeLinecap="round" strokeLinejoin="round" />
<path d="M9.61914 8L16.6191 15L9.61914 22" stroke="#2A2A2A" strokeLinecap="round" strokeLinejoin="round" />
</svg>
</SvgWrap>
```
=> chore: fix figure props

components/index/TodoListItem/index.tsx
#181
위 이슈에 명시된 두가지 버그에 대한 수정을 완료했습니다. 
추가로 focused 상태를 추가했습니다. 이 상태는 추후 -> 투두를 한번 클릭했을 때 강조시키는 용도(css와 함께)로 사용예정입니다. 
https://user-images.githubusercontent.com/63354527/185773158-0256b5d3-74fe-4b36-9823-bf885792e013.mov
=> fix: todolistitem bug 수정

components/common/Sidebar/index.tsx, components/common/Sidebar/styles.tsx, pages/_app.tsx, pages/index.tsx, pages/login/index.tsx, pages/map/index.tsx, shared/types/environment.d.ts
로그인페이지, 지도페이지는 레이아웃이 다릅니다.
예를들어 지도페이지에는 사이드바가 기본레이아웃으로 최상위 컴포넌트에서 선언해버릴 수 있지만 로그인페이지에는 사이드바를 레이아웃에 둘 필요가 없죠.
기존에는 모든 페이지가 사이드바에 대한 레이아웃을 공유해서 로그인 페이지에서 hidden 처리하는등으로 처리했는데 이제 각기 다른 레이아웃을 적용할 수 있게 했습니다.
이제 페이지별로 각기 다른 레이아웃을 활용할 수 있습니다.
아래에 Next.js Layout 공식문서 참고자료 남깁니다.
```ts
// login
Login.getLayout = function getLayout(page: ReactElement) {
return <LoginLayout>{page}</LoginLayout>;
};
```
```ts
// map
Map.getLayout = function getLayout(page: ReactElement) {
return <AppLayout>{page}</AppLayout>;
};
```
https://nextjs.org/docs/basic-features/layouts
=> feat: NextPageLayout

components/index/TodoListItem/index.tsx
기존 체크박스 클릭하면 Todo Focus가 같이 되었는데  이벤트 버블링을 막음으로서 check만 하면 check만되고 같이 focus되는 현상 제거
=> fix: check를 누를 때 todolistitem이 focus되는 현상 수정

docker-compose.yml
mozi.cz에서 환경변수(env) 설정이 안되서 오류가 나던 버그를 수정하려고 docker-compose.yml 파일을 수정하였습니다.
잘 되었으면 좋겠네요...
=> fix: docker compose 환경변수 설정

hooks/apis/todo/useTodoListQuery.ts, pages/trash/index.tsx, shared/types/todo.ts
쿼리 키를 동일하게 유지해 한번의 Fetching으로 데이터를 가져온 후 useSoftDeletedTodoList를 사용하면 필터링된 Todo를 볼 수 있습니다.
관련 내용 블로그 작성했습니다.
- https://velog.io/@hyunjine/React-Query-f910ixmg#3-using-the-select-option
=> feat: useSoftDeletedTodoList

.github/workflows/cd.yml
- CD 하는데 시간이 너무 많이 걸리는데 실은 PR에서 CD를 돌릴 이유가 없습니다.
- Vercel 에서 빌드 체크를 해주니까 그래서 뺐습니다 :)
=> chore: merge 되는 경우만 CD

package.json, src/components/common/Sidebar/index.tsx, src/components/map/SearchSideBar/index.tsx, src/hooks/useSearchSideBar.ts, src/hooks/useSideBar.ts, src/store/localStorage/sidebar.ts, src/store/sidebar/atom.ts, yarn.lock
MOZI-244
SSR에서 localStorage는 없기 때문에 분기해서 처리해야했습니다.
SSR환경에서 렌더링된 상태와 클라이언트 상태에서 렌더링된 상태가 다르면 에러가 발생합니다.
현재 `componentDidMount`시점에 로컬 스토리지를 읽어서 상태를 업데이트하도록 구성되어서 분명히 개선의 여지는 많지만 일단 기능을 완성했기 때문에 올리고 SSR을 처리할 수 있는 방법을 공부해보겠습니다.
또한 recoil-persist를 사용할 큰 이유는 없어서 recoil-persist를 제거하는 방향으로 나아가보겠습니다.
=> feat: recoil-persist를 사용한 사이드바 상태 기억

src/pages/map/index.tsx
MOZI-282
지도가 로딩되기전에 로딩 스피너를 보여줄 수 있습니다. 
카카오 앱에서 지도를 처음에 사진을 먼저 보여주고 사용자가 지루하지 않게 만든 후에 지도가 실제 로딩되면 사용자가 인터랙션 가능한 지도를 보여주는 방법을 사용하는 것을 보았습니다.
https://user-images.githubusercontent.com/63354527/192938792-510c4a5f-1cc1-40fc-b119-310e5634e79c.mov
=> feat: map 페이지 로딩전에 임시 지도 이미지 표시

src/components/upcoming/Calendar/index.tsx, src/components/upcoming/Calendar/styles.tsx, src/hooks/apis/todo/useTodoListQuery.ts, src/pages/upcoming/index.tsx, src/shared/utils/date.ts
달력에서 해당 날짜의 todo를 확인 할 수 있도록 구현하였습니다.
- 해당 날짜에 대한 todo 확인 기능
- 캘린더를 보면 간단한 todo title 확인 가능
=> feat: 달력 클릭시 해당 날짜, 이후의 Todo 보이기

src/components/map/SearchSideBar/RecentSearch/index.tsx, src/components/map/SearchSideBar/RecentSearch/styles.tsx, src/components/map/SearchSideBar/index.tsx
최근 검색어 기능을 검색바 쪽으로 옮기고 남은 자리에는 todolist item을 넣을 예정입니다.
- 최근 검색어 기능 검색바 클릭시 보이게 구현
- 최근 검색어 바깥쪽 클릭시 사라지도록 구현
https://user-images.githubusercontent.com/51700274/197765622-72131bc5-ad5f-493d-a0ac-87906a405fc5.mov
=> refactor: 최근 검색어 기능을 검색바 클릭시 보이도록 구현

src/hooks/apis/todo/useTodoListQuery.ts, src/pages/index.tsx, src/pages/map/index.tsx, src/pages/trash/index.tsx, src/pages/upcoming/index.tsx, src/shared/constants/dialog.ts, src/shared/types/common.ts, src/shared/types/todo.ts, src/worker/index.ts
react-query type, 여러개의 query 한개로 변환
=> refactor: useTodoListQuery 로직 통일 및 타입 추가

src/components/map/SearchSideBar/index.tsx, src/services/apis/location.ts, src/shared/utils/map.ts
기존의 장소 검색 기능의 API End point는 `POST /location/nearby` 였습니다.
이를 `GET /location?keyword={}&longitude={}&latitude={}`로 바꿨습니다.
이에 맞춰서 호출하는 부분도 바꿔줬습니다.
- location search API 호출 방법 변경
`POST` 대신에 `GET`을 사용하니 아주 빨라졌습니다!
=> fix: 장소 검색 성능 향상

src/pages/map/index.tsx
오늘 오프라인 회의때 이야기했던 맵 페이지 바운더리 입니다.
현재 거리와 관련한 todo column이 정의가 되어있지 않아 간단하게 구조만 넣어놓았습니다.
해당 부분이 생기면 리팩토링 진행하겠습니다 :)
=> feat: map 페이지 바운더리 추가
